### ISSUE TITLE
Load local files

### ISSUE THREAD

**Issue by Nineswiss** [skpm/sketch-module-web-view#138]
Within my plugins src file i have the "main/html" which the webview loaded. I have created an "images" and a "css" folder within "src" and am trying to load them into "main.html" but am getting "Not allowed to load local resource".
What is the correct way to load external local css, images etc?

**Comment by scuster1-chwy** [comment]
@Nineswiss, you can't do that because the Sketch plugin (once built) has no idea that the src folder exists. You would need to put those files under the "resources" folder for them to be usable.

If you want a clean separate and automated from src and dist, then you'd have to use something like webpack to manage that.

If this answers your question, please close this issue. If not, then please reply with a followup question.

**Comment by Jakobud** [comment]
I'm missing something here. I have the following layout:

```
resources/window.html
resources/css/bootstrap.css
resources/js/jquery.js
```

And in `window.html` I am trying to load those css and JS files:

```
<link rel="stylesheet" href="./css/bootstrap.css">
```

```
<script src="./js/jquery.js"></script>
```

But I don't think they are loading. What am I missing here?

**Comment by nuthinking** [comment]
@scuster1-chwy what if these files are created at runtime (i.e. exported layers of an artboard)? Can I still populate the resource folder at runtime so that I can load files with relative path instead of `file:///`?
