### ISSUE TITLE
executeJavaScript is called on wrong page

### ISSUE THREAD

**Issue by stefanb0305** [skpm/sketch-module-web-view#149]
I start my plugin by loading a local file called "login.html". But after the user clicks a button on that page, the plugin loads a different local file called "main.html". This is working fine.
The issue is when I try to `executeJavaScript(`function1()`)` after calling `loadURL("../resources/main.html")`. _function1_ is located in "main.js" which is linked to "main.html" but it never gets called. After doing some testing, I realised that the plugin is trying to find the _function1_ in my "login.js" file, which is not what I want. How can I specify which JS file it should use for the executeJS call?

**Comment by mathieudutour** [comment]
you can't there is no concept of "file" in javascript. Everything is in the same context. Your javascript files define global functions that can be called from the plugin.

But what I'm guessing is happening is that `loadURL` takes a few milliseconds before finishing. And in the meantime you call `executeJavaScript` which gets executed on the already loaded page (because it can't know that it should wait for the new page)

**Comment by stefanb0305** [comment]
I see. I implemented a delayed call of the function by using `setTimeOut(function1, 50)` and this has now worked.
Thanks a lot for the reply and help!
