### ISSUE TITLE
Support custom drag region when title bar is hidden

### ISSUE THREAD

**Issue by everdrone** [skpm/sketch-module-web-view#28]
this environment is totally new here, and since there is not much documentation for the whole "sketch plugin development" topic i'm learning by examples.

Managed to make a react ready environment with the help of this module, but with `hideTitleBar` set to `true` i can't find a way to make a draggable area in the UI.

any advice?

**Comment by mathieudutour** [comment]
It's not possible yet. I need to dig into how to do that. Here is how Atom is doing it: https://github.com/electron/electron/blob/master/atom/browser/native_browser_view_mac.mm#L12-L154

**Comment by everdrone** [comment]
nice

thanks for the reference, will look into that

**Comment by tborychowski** [comment]
Any updates on this?

**Comment by canisminor1990** [comment]
Any updates on this?

**Comment by mathieudutour** [comment]
fix in v3.0.0

Instead of `-webkit-app-region: drag;`, you will need to set `data-app-region="drag"` on your div

**Comment by tborychowski** [comment]
There seems to be a problem with the v3.0.0.
When I update the plugin window doesn't even open.
I tried several times to switch between 2.1.7 and 3.0.0 and the former works every time, the latter doesn't (I even commented out all my `executeJavascript` leaving just the bare-bones `BrowserWindow`).

**Comment by mathieudutour** [comment]
Do you have a repro I could try?  The error doesn't seem to be related to this package

**Comment by tborychowski** [comment]
@mathieudutour 
I stripped down my actual plugin to the bare min, and here it is: https://github.com/tborychowski/my-plugin
It works no problem with the older version, but getting this error with v3.

**Comment by mathieudutour** [comment]
That's because of this: https://github.com/tborychowski/my-plugin/blob/master/src/manifest.json#L23. Any reason to set it to `false`? The output from webpack doesn't work well with the cocoascript preprocessor.

Also don't use private APIs https://github.com/tborychowski/my-plugin/blob/master/src/index.js#L22-L25? there are APIs for all of this available

**Comment by tborychowski** [comment]
Thanks @mathieudutour 

1. For the preprocessor - I assumed that when I'm using some CocoaScript  this needs to be enabled :-) (seems to work without it)

2. Yeah, I was playing around with something and forgot to remove it. 

Btw, how do I hide the Minimise and Maximise buttons with the official APIs?
(`maximizable: false` only disables the button for me, instead of hiding it)

It's odd that this works with the older version though.
Anyway - changing the `disableCocoaScriptPreprocessor` to `false` fixes my issue.

Thanks!

**Comment by lucaorio** [comment]
Sorry for commenting this closed issue, but I can't get the window to be draggable.

In my `js`:
```js
const options = {
  identifier: 'unique.id',
  width: 480,
  height: 480,
  center: true,
  show: false,
  backgroundColor: '#171717',
  titleBarStyle: 'hiddenInset',
  resizable: false,
  fullscreenable: false,
  alwaysOnTop: true,
  maximizable: false,
  minimizable: false,
};
```

And in the `html`:
```html
<body data-app-region="drag">
...
</body>
```

Am I doing anything wrong? Is there any option that perhaps causes some sort of conflict?
Thanks!

**Comment by lucaorio** [comment]
I solved my issue: as pointed out on #92, `sketch-module-web-view": "^3.0.1"` is required. 
For anyone who's facing the same problem, make sure to bump the version if you installed this via skpm template (https://github.com/skpm/with-webview).

**Comment by mathieudutour** [comment]
Ah yes, haven't updated the template yet. Happy to accept a PR :)

**Comment by lucaorio** [comment]
@mathieudutour Sounds good! 👍 https://github.com/skpm/with-webview/pull/16
